spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: p@ssw0rd
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081
  servlet:
    context-path: /auth-server